bank_app/urls.py
from django.urls import path
from . import views
from . import apis

app_name = 'bank_app'

urlpatterns = [
    # Pages 
    path('index', views.index, name='index'),
    path('customer', views.customer, name='customer'),
    path('employee', views.employee, name='employee'),

    # Loan 
    path('loan_details/<int:pk>', views.loan_details, name='loan_details'),
    path('request_loan', views.request_loan, name='request_loan'),
    path('get_loans_partial/<int:pk>', views.get_loans_partial, name='get_loans_partial'),
    path('get_loans_partial/', views.get_loans_partial, name='get_loans_partial'),
    path('set_loan_status/<int:pk>/<str:new_status>/', views.set_loan_status, name='set_loan_status'),
    path('get_loan_status/<int:pk>/', views.get_loan_status, name='get_loan_status'),
    path('get_loan_actions/<int:pk>/', views.get_loan_actions, name='get_loan_actions'),

    # Account
    path('create_account', views.create_account, name='create_account'),
    path('account_details/<uuid:pk>', views.account_details, name='account_details'),
    path('get_accounts_partial/<int:pk>', views.get_accounts_partial, name='get_accounts_partial'),
    path('get_account_movements_partial/<uuid:pk>', views.get_account_movements_partial, name='get_account_movements_partial'),
    path('create_transfer', views.create_transfer, name='create_transfer'),
    path('api/external_transfer', apis.external_transfer, name="external_transfer"),

    # Customer 
    path('get_customers_partial', views.get_customers_partial, name='get_customers_partial'),
    path('create_customer', views.create_customer, name='create_customer'),
    path('customer_details/<int:pk>', views.customer_details, name='customer_details'),
    path('set_rank', views.set_rank, name='set_rank'),

    # Users
    path('logout', views.logout, name='logout'),

    # Transaction PDF
    path('download_receipt/<uuid:transaction_id>', views.download_receipt, name='download_receipt'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from two_factor.views import LoginView, SetupView
from two_factor.urls import urlpatterns as tf_urls

from bank_app.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bank/', include('bank_app.urls')),
    
    # 2FA
    path('', include(tf_urls)),
    path('', index, name='login'),
    path('setup/', SetupView.as_view(), name='setup'),

    # REST API
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

bank_app/views.py
import io
from django.shortcuts import render, get_object_or_404
from .models import Account, Customer, Ledger, Loan
from django.contrib.auth import logout as dj_logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.conf import settings
from django.http import FileResponse
from reportlab.pdfgen import canvas
from datetime import date


def is_employee(user):
    return True if hasattr(user, 'employee') else False


def is_customer(user):
    return True if hasattr(user, 'customer') else False


def index(request):
    if request.user.is_authenticated:
        if not request.user.is_verified():
            # user not logged in using two-factor
            return HttpResponseRedirect(reverse('two_factor:setup'))

        # if user is employee, should not access /customer.html
        if is_customer(request.user):
            return HttpResponseRedirect(reverse('bank_app:customer'))
        elif is_employee(request.user):
            return HttpResponseRedirect(reverse('bank_app:employee'))
        else:
            logout(request)
            return HttpResponseRedirect(reverse('two_factor:login'))

    else:
        return HttpResponseRedirect(reverse('two_factor:login'))


@user_passes_test(is_customer, login_url='/')
def customer(request):
    context = {
        'customer': request.user.customer, 
        'bank_registration_number': settings.BANK_REGISTRATION_NUMBER
    }

    return render(request, 'bank_app/pages/customer/customer.html', context)


@user_passes_test(is_employee, login_url='/')
def employee(request):
    return render(request, 'bank_app/pages/employee/employee.html')


@user_passes_test(is_employee, login_url='/')
def customer_details(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    context = {
        'customer': customer
    }

    return render(request, 'bank_app/pages/employee/customer_details.html', context)


@user_passes_test(is_employee, login_url='/')
def get_customers_partial(request):
    customers = Customer.objects.all()
    context = {
        'customers': customers
    }

    return render(request, 'bank_app/partials/employee/customers_list.html', context)


@user_passes_test(is_employee, login_url='/')
def create_customer(request):
    if not request.method == 'POST':
        return HttpResponseRedirect(reverse('bank_app:index'))

    username = request.POST['username']
    first_name = request.POST['first_name']
    last_name = request.POST['last_name']
    phone = request.POST['phone']
    email = request.POST['email']
    password = request.POST['password']

    customer = Customer.create(username, first_name, last_name, phone, email, password)
    context = {
        'customers': [customer]
    }

    return render(request, 'bank_app/partials/employee/customers_list.html', context)

@login_required
def get_accounts_partial(request, pk):
    accounts = Account.objects.filter(user=pk)
    context = {
        'accounts': accounts
    }

    return render(request, 'bank_app/partials/accounts_list.html', context)


@user_passes_test(is_employee, login_url='/')
def create_account(request):
    if not request.method == 'POST':
        return HttpResponseRedirect(reverse('bank_app:index'))

    name = request.POST['name']
    pk = request.POST['pk']
    account = Account.create(name=name, pk=pk, is_loan=False)
    context = {
        'accounts': [account]
    }

    return render(request, 'bank_app/partials/accounts_list.html', context)
        

@user_passes_test(is_employee, login_url='/')
def set_rank(request):
    if not request.method == 'POST':
        return HttpResponseRedirect(reverse('bank_app:index'))

    pk = request.POST['pk']
    rank = request.POST['rank']
    customer = get_object_or_404(Customer, pk=pk)
    customer.set_rank(pk, rank)
    context = {
        'text': rank
    }

    return render(request, 'bank_app/partials/text.html', context)
    

@user_passes_test(is_customer, login_url='/')
def create_transfer(request):
    if not request.method == 'POST':
        return HttpResponseRedirect(reverse('bank_app:index'))

    from_account_id = request.POST['from_account_id']
    from_text = request.POST['from_text']

    to_account_id = request.POST['to_account_id']
    to_text = request.POST['to_text']
    to_registraton_number = request.POST['to_registraton_number']

    amount = float(request.POST['amount'])
    internal_bank_registration_number = settings.BANK_REGISTRATION_NUMBER
    banks = settings.BANKS

    context = {
        'customer': request.user.customer,
    }

    # Not internal transfer and external transfer
    if not to_registraton_number in banks and to_registraton_number != internal_bank_registration_number:
        context['message'] = {
            'text': 'Account does not exist',
            'type': 'error'
        }
        response = render(request, 'bank_app/partials/message.html', context)

    # Internal transfer
    elif to_registraton_number == internal_bank_registration_number:
        try:
            transaction_id = Ledger.internal_transfer(amount, from_account_id, to_account_id, from_text, to_text)
            context['message'] = {
                'text': 'Your money was transfered successfully',
                'type': 'success'
            }
            context['pdf_download'] = True
            context['transaction_id'] = transaction_id

            response = render(request, 'bank_app/partials/message.html', context)
            response.headers["HX-Trigger"] = "accountUpdate"
            
        except:
            context['message'] = {
                'text': 'Not enough money on account',
                'type': 'error'
            }

            response = render(request, 'bank_app/partials/message.html', context)
            response.headers["HX-Trigger"] = "accountUpdate"

    # Send external transfer
    else:
        transaction = Ledger.external_transfer(amount, from_account_id, to_account_id, from_text, to_text, to_registraton_number)
        context['message'] = transaction['message']
        
        if 'id' in transaction:
            context['pdf_download'] = True
            context['transaction_id'] = transaction['id']

        response = render(request, 'bank_app/partials/message.html', context)
        response.headers["HX-Trigger"] = "accountUpdate"

    return response


@user_passes_test(is_customer, login_url='/')
def request_loan(request):
    if not request.method == 'POST':
        return HttpResponseRedirect(reverse('bank_app:index'))

    name = request.POST['name']
    amount = float(request.POST['amount'])
    to_account_id = request.POST['to_account_id']

    context = {
        'customer': request.user.customer,
    }

    if not Account.objects.filter(pk=to_account_id).exists():
        context['message'] = {
            'text': 'Account does not exist.',
            'type': 'error'
        }
        return render(request, 'bank_app/partials/message.html', context)

    if not request.user.customer.can_make_loan:
        context['message'] = {
            'text': 'You are not high enough rank to make a loan. Please contact us.',
            'type': 'error'
        }
    else:
        context['message'] = {
            'text': 'You have successfully requested a loan. You will hear from us soon.',
            'type': 'success'
        }

    Loan.request(
        amount=amount,
        name=name, 
        user=request.user,
        to_account_id=to_account_id
    )

    response = render(request, 'bank_app/partials/message.html', context)
    response.headers["HX-Trigger"] = "loanUpdate"
    
    return response


@login_required
def get_loans_partial(request, pk=None):
    if is_employee(request.user):
        if pk:
            loans = Loan.objects.filter(user=pk)
        else:
            loans = Loan.objects.all()
        template = 'employee'
    else:
        loans = Loan.objects.filter(user=pk)
        template = 'customer'

    context = {
        'loans': loans 
    }
    
    return render(request, f'bank_app/partials/{template}/loans_list.html', context)


@user_passes_test(is_employee, login_url='/')
def set_loan_status(request, pk, new_status):
    if not request.method == 'POST':
        return HttpResponseRedirect(reverse('bank_app:index'))

    loan = get_object_or_404(Loan, pk=pk)

    if loan.status == "ACCEPTED" or loan.status == "DECLINED":
        context = { 
            'loan': loan, 
            'message': { 
                'text': f"Loan is already {loan.status}", 'type': 'error' 
            }
        }

        return render(request, 'bank_app/partials/message.html', context)

    if new_status == "ACCEPTED":
        loan.create(name=loan.name, customer_pk=loan.user.pk, amount=loan.amount, to_account_id=loan.to_account_id)

    loan.set_status(pk, new_status)

    context = {
        'loan': loan, 
        'message': { 
            'text': f"Loan status changed to {new_status}", 'type': 'success' 
        }
    }

    response = render(request, 'bank_app/partials/message.html', context)
    response.headers["HX-Trigger"] = "loanUpdate"

    return response


@user_passes_test(is_employee, login_url='/')
def get_loan_status(request, pk):
    loan = get_object_or_404(Loan, pk=pk)

    context = {
        'message': {
            'text': loan.status,
            'type': Loan.STATUS_COLORS[loan.status]
        }
    }

    return render(request, 'bank_app/partials/employee/loan_status.html', context)


@user_passes_test(is_employee, login_url='/')
def get_loan_actions(request, pk):
    loan = get_object_or_404(Loan, pk=pk)
    showActions = True if loan.status == 'PENDING' else False

    context = {
        'loan': loan,
        'showActions': showActions
    }

    return render(request, 'bank_app/partials/employee/loan_actions.html', context)


@user_passes_test(is_employee, login_url='/')
def loan_details(request, pk):

bank_app/templates/bank_app/pages/customer/customer.html
{% extends '../../base.html' %}

{% block content %}
<h1>
    Hello {{customer.user.first_name}}!
</h1>
<p>Rank: {{customer.rank}}</p>

<h2>Accounts</h2>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Is loan</th>
      <th>Balance</th>
    </tr>
  </thead>
  <tbody
    id="accounts_list"
    hx-swap="innerHTML"
    hx-get="{% url 'bank_app:get_accounts_partial' customer.pk %}"
    hx-trigger="load, accountUpdate from:body"
  ></tbody>
</table>

<h2>Loans</h2>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Amount</th>
      <th>Status</th>
      <th>Created at</th>
    </tr>
  </thead>
  <tbody
    id="accounts_list"
    hx-swap="innerHTML"
    hx-get="{% url 'bank_app:get_loans_partial' customer.pk %}"
    hx-trigger="load, loanUpdate from:body"
  ></tbody>
</table>

<h2>Transfer money</h2>
<form style="display: flex; flex-direction: column; align-items: flex-start; gap: 10px;">
    {% csrf_token %}
    <input name="bank_registration_number" type="hidden" value="{{ bank_registration_number }}" />
    <fieldset>
        <legend>From</legend>
        <label style="display: flex; flex-direction: column; align-items: flex-start;">
            <span>Account</span>
            <select required name="from_account_id">
                <option value=""></option>
                {% for account in customer.accounts %}
                    {% if not account.is_loan%}
                        <option value="{{account.pk}}">{{account.name}}</option>
                    {% endif %}
                {% endfor %}
            </select>
        </label>
        <label style="display: flex; flex-direction: column; align-items: flex-start;">
            <span>Text on account statement</span>
            <input required name="from_text" type="text" />
        </label>
        <label style="display: flex; flex-direction: column; align-items: flex-start;">
            <span>Amount</span>
            <input required name="amount" type="number" placeholder="Enter amount" />
        </label>
    </fieldset>
    <fieldset>
        <legend>To</legend>
        <div style="display: flex; gap: 10px;">
            <label style="display: flex; flex-direction: column; align-items: flex-start;">
                <span>Account</span>
                <select class="accounts" name="accounts">
                    <option value=""></option>
                    {% for account in customer.accounts %}
                    <option value="{{account.pk}}">{{account.name}}</option>
                    {% endfor %}
                </select>
            </label>
            <p>Or</p>
            <label style="display: flex; flex-direction: column; align-items: flex-start;">
                <span>Account number</span>
                <input required class="to_account_id" name="to_account_id" type="text" placeholder="Enter account number"/>
            </label>
            <label style="display: flex; flex-direction: column; align-items: flex-start;">
                <span>Registration number</span>
                <input required class="to_registraton_number" name="to_registraton_number" type="text" placeholder="Enter registration number"/>
            </label>
        </div>
        <label style="display: flex; flex-direction: column; align-items: flex-start;">
            <span>Text on receiver statement</span>
            <input name="to_text" type="text"/>
        </label>
    </fieldset>
    <button
        hx-post="{% url 'bank_app:create_transfer' %}"
        hx-trigger="click"
        hx-swap="innerHTML"
        hx-target="#message"
    >Transfer</button>
    <div id="message"></div>
</form>

{% if customer.can_make_loan %}
    <h2>Request loan</h2>
    <form>
        {% csrf_token %}
        <input name="bank_registration_number" type="hidden" value="{{ bank_registration_number }}" />
        <fieldset>
            <label style="display: flex; flex-direction: column; align-items: flex-start;">
                <span>Amount</span>
                <input name="amount" type="number" placeholder="Enter amount"/>
            </label>
            <label style="display: flex; flex-direction: column; align-items: flex-start;">
                <span>Name on loan</span>
                <input name="name" type="text" placeholder="Enter name"/>
            </label>
            <div style="display: flex; gap: 10px;">
                <label style="display: flex; flex-direction: column; align-items: flex-start;">
                    <span>To account</span>
                    <select name="to_account_id">
                        <option value=""></option>
                        {% for account in customer.accounts %}
                            {% if not account.is_loan %}
                                <option value="{{account.pk}}">{{account.name}}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </label>
            </div>
        </fieldset>
        <button
            hx-post="{% url 'bank_app:request_loan' %}"
            hx-trigger="click"
            hx-swap="innerHTML"
            hx-target="#loan_message"
        >
            Request loan
        </button>
        <div id="loan_message"></div>
    </form>
{% endif %}


<script defer>
    const select = document.querySelectorAll(".accounts");

    select.forEach(select => {
        const form = select.closest("form");
        
        select.addEventListener("change", (e) => {
            const accountNumberInput = form.querySelector(".to_account_id");
            const regNumberInput = form.querySelector(".to_registraton_number");
            const bankRegNumber = form.querySelector('input[name="bank_registration_number"]');
            
            regNumberInput.value = bankRegNumber.value;
            accountNumberInput.value = e.target.value;
        });
    });
</script>
{% endblock %}